# DATA PRE-PROCESSING

In [1]:
import pandas as pd
df = pd.read_csv("AMJATH.txt",header=None,on_bad_lines='skip',encoding='utf8')
df

,0,1,2,3
0,4/5/22,6:31 PM - Messages and calls are end-to-end e...,listen to,or share them. Learn more.
1,4/5/22,6:31 PM - Amjath Kncet changed their phone nu...,NaN,NaN
2,4/5/22,8:09 PM - AMJATH: Hi da I'm amjath,NaN,NaN
3,4/5/22,8:09 PM - AMJATH: My new number,NaN,NaN
4,4/6/22,7:01 AM - priyan: 👍,NaN,NaN
...,...,...,...,...
3883,11/1/25,1:45 PM - priyan: https://www.1tamilmv.farm/i...,NaN,NaN
3884,11/1/25,1:45 PM - priyan: https://www.1tamilmv.farm/i...,NaN,NaN
3885,11/1/25,1:45 PM - priyan: https://www.1tamilmv.farm/i...,NaN,NaN
3886,11/1/25,1:45 PM - priyan: https://www.1tamilmv.farm/i...,NaN,NaN
3887,11/1/25,1:48 PM - AMJATH: <Media omitted>,NaN,NaN

In [2]:
df=df.drop(0)

In [3]:
df

            0                                                  1    2    3
1      4/5/22   6:31 PM - Amjath Kncet changed their phone nu...  NaN  NaN
2      4/5/22                 8:09 PM - AMJATH: Hi da I'm amjath  NaN  NaN
3      4/5/22                    8:09 PM - AMJATH: My new number  NaN  NaN
4      4/6/22                                7:01 AM - priyan: 👍  NaN  NaN
5     5/24/22                 10:56 AM - AMJATH: <Media omitted>  NaN  NaN
...       ...                                                ...  ...  ...
3883  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...  NaN  NaN
3884  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...  NaN  NaN
3885  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...  NaN  NaN
3886  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...  NaN  NaN
3887  11/1/25                  1:48 PM - AMJATH: <Media omitted>  NaN  NaN

[3887 rows x 4 columns]

In [4]:
df=df.drop(1)
df

            0                                                  1    2    3
2      4/5/22                 8:09 PM - AMJATH: Hi da I'm amjath  NaN  NaN
3      4/5/22                    8:09 PM - AMJATH: My new number  NaN  NaN
4      4/6/22                                7:01 AM - priyan: 👍  NaN  NaN
5     5/24/22                 10:56 AM - AMJATH: <Media omitted>  NaN  NaN
6     8/12/22           4:47 PM - AMJATH: http://tpcg.io/_YE2YX0  NaN  NaN
...       ...                                                ...  ...  ...
3883  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...  NaN  NaN
3884  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...  NaN  NaN
3885  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...  NaN  NaN
3886  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...  NaN  NaN
3887  11/1/25                  1:48 PM - AMJATH: <Media omitted>  NaN  NaN

[3886 rows x 4 columns]

In [5]:
df.drop([2, 3], axis=1, inplace=True)

In [6]:
df

            0                                                  1
2      4/5/22                 8:09 PM - AMJATH: Hi da I'm amjath
3      4/5/22                    8:09 PM - AMJATH: My new number
4      4/6/22                                7:01 AM - priyan: 👍
5     5/24/22                 10:56 AM - AMJATH: <Media omitted>
6     8/12/22           4:47 PM - AMJATH: http://tpcg.io/_YE2YX0
...       ...                                                ...
3883  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...
3884  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...
3885  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...
3886  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...
3887  11/1/25                  1:48 PM - AMJATH: <Media omitted>

[3886 rows x 2 columns]

In [7]:
df.columns=['Date','Chat']

In [8]:
df

         Date                                               Chat
2      4/5/22                 8:09 PM - AMJATH: Hi da I'm amjath
3      4/5/22                    8:09 PM - AMJATH: My new number
4      4/6/22                                7:01 AM - priyan: 👍
5     5/24/22                 10:56 AM - AMJATH: <Media omitted>
6     8/12/22           4:47 PM - AMJATH: http://tpcg.io/_YE2YX0
...       ...                                                ...
3883  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...
3884  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...
3885  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...
3886  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...
3887  11/1/25                  1:48 PM - AMJATH: <Media omitted>

[3886 rows x 2 columns]

In [9]:
Message=df['Chat'].str.split('-',n=1,expand=True)
Message

               0                                                  1
2       8:09 PM                            AMJATH: Hi da I'm amjath
3       8:09 PM                               AMJATH: My new number
4       7:01 AM                                           priyan: 👍
5      10:56 AM                             AMJATH: <Media omitted>
6       4:47 PM                      AMJATH: http://tpcg.io/_YE2YX0
...          ...                                                ...
3883    1:45 PM    priyan: https://www.1tamilmv.farm/index.php?/...
3884    1:45 PM    priyan: https://www.1tamilmv.farm/index.php?/...
3885    1:45 PM    priyan: https://www.1tamilmv.farm/index.php?/...
3886    1:45 PM    priyan: https://www.1tamilmv.farm/index.php?/...
3887    1:48 PM                             AMJATH: <Media omitted>

[3886 rows x 2 columns]

In [10]:
df['Time']=Message[0]
df

         Date                                               Chat        Time
2      4/5/22                 8:09 PM - AMJATH: Hi da I'm amjath    8:09 PM
3      4/5/22                    8:09 PM - AMJATH: My new number    8:09 PM
4      4/6/22                                7:01 AM - priyan: 👍    7:01 AM
5     5/24/22                 10:56 AM - AMJATH: <Media omitted>   10:56 AM
6     8/12/22           4:47 PM - AMJATH: http://tpcg.io/_YE2YX0    4:47 PM
...       ...                                                ...         ...
3883  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...    1:45 PM
3884  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...    1:45 PM
3885  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...    1:45 PM
3886  11/1/25   1:45 PM - priyan: https://www.1tamilmv.farm/i...    1:45 PM
3887  11/1/25                  1:48 PM - AMJATH: <Media omitted>    1:48 PM

[3886 rows x 3 columns]

In [11]:
Message1=Message[1].str.split(':',n=1,expand=True)
Message1

            0                                                  1
2      AMJATH                                   Hi da I'm amjath
3      AMJATH                                      My new number
4      priyan                                                  👍
5      AMJATH                                    <Media omitted>
6      AMJATH                             http://tpcg.io/_YE2YX0
...       ...                                                ...
3883   priyan   https://www.1tamilmv.farm/index.php?/forums/t...
3884   priyan   https://www.1tamilmv.farm/index.php?/forums/t...
3885   priyan   https://www.1tamilmv.farm/index.php?/forums/t...
3886   priyan   https://www.1tamilmv.farm/index.php?/forums/t...
3887   AMJATH                                    <Media omitted>

[3886 rows x 2 columns]

In [12]:
df['Name']=Message1[0]
df['Chat']=Message1[1]

In [13]:
df

,Date,Chat,Time,Name
2,4/5/22,Hi da I'm amjath,8:09 PM,AMJATH
3,4/5/22,My new number,8:09 PM,AMJATH
4,4/6/22,👍,7:01 AM,priyan
5,5/24/22,<Media omitted>,10:56 AM,AMJATH
6,8/12/22,http://tpcg.io/_YE2YX0,4:47 PM,AMJATH
...,...,...,...,...
3883,11/1/25,https://www.1tamilmv.farm/index.php?/forums/t...,1:45 PM,priyan
3884,11/1/25,https://www.1tamilmv.farm/index.php?/forums/t...,1:45 PM,priyan
3885,11/1/25,https://www.1tamilmv.farm/index.php?/forums/t...,1:45 PM,priyan
3886,11/1/25,https://www.1tamilmv.farm/index.php?/forums/t...,1:45 PM,priyan
3887,11/1/25,<Media omitted>,1:48 PM,AMJATH

In [14]:
df=df[['Date','Time','Name','Chat']]
df

,Date,Time,Name,Chat
2,4/5/22,8:09 PM,AMJATH,Hi da I'm amjath
3,4/5/22,8:09 PM,AMJATH,My new number
4,4/6/22,7:01 AM,priyan,👍
5,5/24/22,10:56 AM,AMJATH,<Media omitted>
6,8/12/22,4:47 PM,AMJATH,http://tpcg.io/_YE2YX0
...,...,...,...,...
3883,11/1/25,1:45 PM,priyan,https://www.1tamilmv.farm/index.php?/forums/t...
3884,11/1/25,1:45 PM,priyan,https://www.1tamilmv.farm/index.php?/forums/t...
3885,11/1/25,1:45 PM,priyan,https://www.1tamilmv.farm/index.php?/forums/t...
3886,11/1/25,1:45 PM,priyan,https://www.1tamilmv.farm/index.php?/forums/t...
3887,11/1/25,1:48 PM,AMJATH,<Media omitted>

# SENTIMENTAL ANALYSIS

In [15]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [16]:
data=df
data

,Date,Time,Name,Chat
2,4/5/22,8:09 PM,AMJATH,Hi da I'm amjath
3,4/5/22,8:09 PM,AMJATH,My new number
4,4/6/22,7:01 AM,priyan,👍
5,5/24/22,10:56 AM,AMJATH,<Media omitted>
6,8/12/22,4:47 PM,AMJATH,http://tpcg.io/_YE2YX0
...,...,...,...,...
3883,11/1/25,1:45 PM,priyan,https://www.1tamilmv.farm/index.php?/forums/t...
3884,11/1/25,1:45 PM,priyan,https://www.1tamilmv.farm/index.php?/forums/t...
3885,11/1/25,1:45 PM,priyan,https://www.1tamilmv.farm/index.php?/forums/t...
3886,11/1/25,1:45 PM,priyan,https://www.1tamilmv.farm/index.php?/forums/t...
3887,11/1/25,1:48 PM,AMJATH,<Media omitted>

In [17]:
data.dropna(inplace=True)

/var/folders/qc/j1zhz5wd799gnfl61hmhl4kw0000gn/T/ipykernel_1786/1368182302.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dropna(inplace=True)

In [18]:
sid=SentimentIntensityAnalyzer()

In [24]:
 def sentimentalAnalysis(data,columnname):
        from nltk.sentiment.vader import SentimentIntensityAnalyzer
        data.dropna(inplace=True)
        sid = SentimentIntensityAnalyzer()
        data = data.dropna(subset=[columnname])
        data['scores'] = data[columnname].apply(lambda commentText: sid.polarity_scores(commentText))
        data['compound']  = data['scores'].apply(lambda score_dict: score_dict['compound'])
        data['Negtive']  = data['scores'].apply(lambda score_dict: score_dict['neg'])
        data['Postive']  = data['scores'].apply(lambda score_dict: score_dict['pos'])
        data['Neutral']  = data['scores'].apply(lambda score_dict: score_dict['neu'])
        data['comp_score'] = data['compound'].apply(lambda c: 'pos' if c >=0 else 'neg')
        posneg=pd.DataFrame(data['comp_score'].value_counts())
        return posneg,data

In [25]:
print(data.columns)

Index(['Date', 'Time', 'Name', 'Chat'], dtype='object')

In [26]:
pos,data_Senti=sentimentalAnalysis(data,columnname='Chat')

/var/folders/qc/j1zhz5wd799gnfl61hmhl4kw0000gn/T/ipykernel_1786/2738220752.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dropna(inplace=True)

In [27]:
data_Senti

,Date,Time,Name,Chat,scores,compound,Negtive,Postive,Neutral,comp_score
2,4/5/22,8:09 PM,AMJATH,Hi da I'm amjath,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos
3,4/5/22,8:09 PM,AMJATH,My new number,"{'neg': 0.0, 'neu': 0.606, 'pos': 0.394, 'comp...",0.0772,0.0,0.394,0.606,pos
4,4/6/22,7:01 AM,priyan,👍,"{'neg': 0.0, 'neu': 0.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,0.000,pos
5,5/24/22,10:56 AM,AMJATH,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos
6,8/12/22,4:47 PM,AMJATH,http://tpcg.io/_YE2YX0,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos
...,...,...,...,...,...,...,...,...,...,...
3883,11/1/25,1:45 PM,priyan,https://www.1tamilmv.farm/index.php?/forums/t...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos
3884,11/1/25,1:45 PM,priyan,https://www.1tamilmv.farm/index.php?/forums/t...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos
3885,11/1/25,1:45 PM,priyan,https://www.1tamilmv.farm/index.php?/forums/t...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos
3886,11/1/25,1:45 PM,priyan,https://www.1tamilmv.farm/index.php?/forums/t...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos
3887,11/1/25,1:48 PM,AMJATH,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos

In [28]:
pos

            count
comp_score
pos          3703
neg            69